server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_proxied any;
    gzip_types application/json application/ld+json application/javascript text/css image/svg+xml;
    location /api/ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /app/public/index.php;
        fastcgi_param DOCUMENT_ROOT /app/public;
        fastcgi_param HTTPS $https if_not_empty;
        fastcgi_pass backend:9000;
    }
    location / { try_files $uri $uri/ /index.html; }
}
